  install.packages("readr")
  library(readr)
  wiki_clean <- read_csv("wiki_clean.csv", col_types = cols(X1 = col_skip()))
  library(igraph)
  source("getNodeList.R")
  source("graphFunctions.R")
  nodes <- getNodeList(wiki_clean[1:2])
  edges <- getEdgeList(wiki_clean[1:2])
  wgraph <- graph_from_data_frame(d = edges, vertices = nodes, directed = TRUE)
  simplegraph <- simplify(wgraph)
  save.image("~/Desktop/Group-1-Project-1/Project_1_Workspace/Project_1_Workspace.RData")
